function [fitresult, gof] = exp_tau(ss, plotflag)
%CREATEFIT(SS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: ss
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Oct-2018 15:56:01


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], ss );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [-2.68485319244391 -0.000676560325568526];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

if plotflag==1% Plot fit with data.
    figure(33);
    h = plot( fitresult, xData, yData );
    legend( h, 'raw data', 'exp fit', 'Location', 'NorthEast' );
    % Label axes
    ylabel Amplitude
    grid on
    pause
end

